### ISSUE TITLE
Error when generating doc

### ISSUE THREAD

**Issue by minhdanh** [lsegal/yard-js#1]
Hi, I've cloned the project and run bundle install to install dependencies, but as I ran the command to generate document, this is what is got:
yard -m markdown -e ../yard-js/lib/yard-js
[error]: The file `../yard-js/lib/yard-js' could not be loaded:
cannot load such file -- ../yard-js/lib/yard-js
I tried replacing the relative path above with an absolute path but still the same error.
How should I deal with this?

**Comment by KamalPatel365** [comment]
Hi @lsegal  I am getting this unexpected error when I executed the below command
 **bundle exec yard -m markdown -e lib/yard-js.rb** 
------------------------------------------------------------------------------------------------------------------------------------------
bundler: failed to load command: yard (/home/****/.gem/ruby/2.3.0/bin/yard)
RuntimeError: can't modify frozen String
  /home/****/workspace/sdk-documentation/yard/orbipay-paymentsapi-client/src/lib/yard-js/core_ext/yard.rb:9:in `replace'
  /home/****/workspace/sdk-documentation/yard/orbipay-paymentsapi-client/src/lib/yard-js/core_ext/yard.rb:9:in `<top (required)>'
  /home/****/workspace/sdk-documentation/yard/orbipay-paymentsapi-client/src/lib/yard-js/plugin.rb:1:in `require_relative'
  /home/****/workspace/sdk-documentation/yard/orbipay-paymentsapi-client/src/lib/yard-js/plugin.rb:1:in `<top (required)>'
  lib/yard-js.rb:2:in `require_relative'
  lib/yard-js.rb:2:in `<top (required)>'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in `load'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in `load_script'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:28:in `block in common_options'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1571:in `block in parse_in_order'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1613:in `permute!'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1635:in `parse!'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:56:in `parse_options'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:535:in `optparse'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardopts_command.rb:42:in `parse_arguments'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:292:in `parse_arguments'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:248:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:14:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:72:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:54:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/bin/yard:13:in `<top (required)>'
  /home/****/.gem/ruby/2.3.0/bin/yard:23:in `load'
  /home/****/.gem/ruby/2.3.0/bin/yard:23:in `<top (required)>'

**Comment by KamalPatel365** [comment]
Hi @lsegal, could you please help me in resolving this bellow error.
Command: **bundle exec yard -m markdown -e lib/yard-js.rb **
***************************************************************************
bundler: failed to load command: yard (/home/****/.gem/ruby/2.3.0/bin/yard)
RuntimeError: can't modify frozen String
  /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/core_ext/yard.rb:9:in `replace'
  /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/core_ext/yard.rb:9:in `<top (required)>'
  /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/plugin.rb:1:in `require_relative'
  /home/****/workspace/sdk-documentation/yard/****/src/lib/yard-js/plugin.rb:1:in `<top (required)>'
  lib/yard-js.rb:2:in `require_relative'
  lib/yard-js.rb:2:in `<top (required)>'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in `load'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:70:in `load_script'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:28:in `block in common_options'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1571:in `block in parse_in_order'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1613:in `permute!'
  /usr/local/lib/ruby/2.3.0/optparse.rb:1635:in `parse!'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:56:in `parse_options'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:535:in `optparse'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardopts_command.rb:42:in `parse_arguments'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:292:in `parse_arguments'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/yardoc.rb:248:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command.rb:14:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:72:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/lib/yard/cli/command_parser.rb:54:in `run'
  /home/****/.gem/ruby/2.3.0/gems/yard-0.9.25/bin/yard:13:in `<top (required)>'
  /home/****/.gem/ruby/2.3.0/bin/yard:23:in `load'
  /home/****/.gem/ruby/2.3.0/bin/yard:23:in `<top (required)>'

**Comment by KamalPatel365** [comment]
Hi @minhdanh Did you encountered anything like this below ?
**bundle exec yard -m markdown -e lib/yard-js.rb --define-class-expr inherit**
bundler: failed to load command: yard (/usr/local/bin/yard)
/home/****/workspace/sdk-documentation/yard/yard-js/lib/yard-js/core_ext/yard.rb:9:in `replace': can't modify frozen String (RuntimeError)
	from /home/****/workspace/sdk-documentation/yard/yard-js/lib/yard-js/core_ext/yard.rb:9:in `<top (required)>'
